spring.application.name=reconciliation-engine

server.servlet.context-path=/api/v1
server.port=8081

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/v3/api-docs

spring.datasource.url=${POSTGRES_DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

paga.base-url=${PAGA_BASE_URL}
paga.secret-key=${PAGA_SECRET_KEY}
paga.public-key=${PAGA_PUBLIC_KEY}

paga.auth-header=${PAGA_AUTH_HEADER}
paga.webhook-secret=${PAGA_WEBHOOK_SECRET}
webhook-callback-url=${WEBHOOK_CALLBACK_URL}

payment-payload.secret-key=${PAYMENT_PAYLOAD_SECRET_KEY}