spring.application.name=reconciliation-engine

paga.base-url=${PAGA_BASE_URL}
paga.secret-key=${PAGA_SECRET_KEY}
paga.public-key=${PAGA_PUBLIC_KEY}

paga.auth-header=${PAGA_AUTH_HEADER}
paga.webhook-secret=${PAGA_WEBHOOK_SECRET}
webhook-callback-url=${WEBHOOK_CALLBACK_URL}